### ISSUE TITLE
Add "sync" products feature

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#175]
In channels config add "sync all" button what will go through entire channel catalogue of products and send/overwrte them in each CMS
Add CMS links to metadata in Saleor too.

For now make it on the frontend side, later it will be moved to queues

**Comment by orzechdev** [comment]
# Note to address in this task

Currently CMS app is implemented to require in CMS providers objects that represent product variants data level, not products data level.

## Fetching product variants before upload to CMS providers

Quering product variants needs filtering them by channel. `productVariants` query although returns also product variants that have not that channel in channel listings (I understand it returns them because channel is assigned to product channel listings, not variant channel listing). There are three options to address this:
1. Query products filtered by channel (`query products(channel: "abcde")`) and filter their variants in the app again also by channel
2. Implement filtering in `productVariants` query by product variant channel in Saleor Core GraphQL (API changes that need to be discussed in Core repository)
3. Change the objects structure in CMS providers to represent them as products instead of variants (a. it will complicate things more in the current CMS app development, so I would leave it for later, b. if so, product variant channels availability needs to be discussed before approving objects structure, even creating RFC to consider different scenarios).

### Proposition

Do 1. (quickest) and discuss 2. with Core. Open discussion on 3.

**Comment by lkostrowski** [comment]
Check https://docs.saleor.io/docs/3.x/developer/export/export-products

**Comment by orzechdev** [comment]
PR https://github.com/saleor/apps/pull/351

**Comment by orzechdev** [comment]
QA test scenarios https://github.com/saleor/apps/issues/372
