### ISSUE TITLE
Can't install tax app

### ISSUE THREAD

**Issue by mociepka** [saleor/apps#277]
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/1870738/224650852-d3c799d1-b2c8-4ef8-89de-48db8139359e.png">

dashboard v3.12.1
core v3.12.3

**Comment by lkostrowski** [comment]
Seems that issue is not related to the Taxes App - use needs `HANDLE_TAXES` permission

**Comment by lkostrowski** [comment]
After the investigation
1. User who installs the app must have all permissions that app itself requires. Otherwise, user with MANAGE_APPS can create himself a token that will be more powerful than himself - causing permissions leak
2. Admin should automatically have assigned HANDLE_TAXES permission here, this is a bug in Saleor cloud cc @slawekmarszalek 

AFAIK bug is already known to the cloud, so I will close this one, its not related to taxes

I will work on better docs and error messages so this situation is clear for the user
