### ISSUE TITLE
Implement more facet fields to Algolia app

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#893]
>we need all fields, that are important for shop facets to be located in Algolia, as these parts of the page are created with algolia / search data. We want to have facets for "user review stars count", "price facet", "categories", "availability". Just as a feedback on that. These are the most important fields for us.
Price facet is for example "above 10$, above 20$"..
Price ranges is just a regular range filter, but for that we do need the actual, discounted price as well. Not only the gross price.

_Originally posted by @JannikZed in https://github.com/saleor/apps/issues/836#issuecomment-1669676273_

**Comment by lkostrowski** [comment]
@krzysztofwolski please verify 

@JannikZed do you recognize any more fields you like to have?

**Comment by JannikZed** [comment]
I'm giving you some context on the price facet. Here is the design, that we need to implement:
<img width="311" alt="image" src="https://github.com/saleor/apps/assets/7526174/4f2d874d-2bfb-4ed6-87de-a56a3626882b">
The designer wants to enable a selection of priceranges, so that customers can select multiple ranges. This is hard to build "generic", as every shop might have different price categories and you will need to define the ranges manually. So I don't know, if you have some ideas on that.
I can't think of any more facets for the moment, but I will let you know.

**Comment by krzysztofwolski** [comment]
Price ranges as metadata: not a fan. It's going to add additional responsibility for the app, generate additional traffic (price change will trigger additional update event). Don't think that's the right choice for this issue.

UI for the configuration: Theres a lot of options and approaches. Not sure if we have resources to create robust solution right now - even the Algolia dashboard gives basic configuration and suggest using the API directly for detailed configuration ;). As an improvement we could do right now is to add button for non-configurable example filters. It would solve basic needs and give a good starting point for further customization with the API.

@JannikZed Have you seen [Algolia examples docs](https://www.algolia.com/search-inspiration-library/?refinementList%5BuseCase%5D%5B0%5D=eCommerce&page=1&configure%5BhitsPerPage%5D=9&indices%5BPROD_algolia_com-inspiration-library_query_suggestions%5D%5Bconfigure%5D%5BhitsPerPage%5D=6&indices%5BPROD_algolia_com-inspiration-library_query_suggestions%5D%5Bpage%5D=1&query=filter)? Customized price buckets can be implemented with the API https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/how-to/filter-by-numeric-value/#filtering-by-price-range

**Comment by tilman** [comment]
Hey @krzysztofwolski, thanks for the docs. Actually I haven't seen the range feature `number: X to Y`. I played a bit arround with it and together with an undocumented algolia feature I was able to create a numericFilter with multiple price ranges active. Therefore we can also implement the price range filter without any hardcoded facets. Initially I tried out `number>X & number < Y` wich was only working for one price range because it was not possible to combine multiple ranges with the >X/<Y filtering.

I think the priceRange facet is therefore not needed anymore because It is better when the configuration of the ranges can be done dynamically and is configured in the frontend. Only thing wich is missing now is that we only have the grossPrice but would need the discountedGrossPrice. But I guess this is on another issue?

**Comment by tilman** [comment]
Combined as and: 
`numericFilters: ["grossPrice: 10 to 12", "grossPrice: 50 to 60"]`

Combined as or (and therefore possible to filter multiple ranges as needed): 
`numericFilters: [["grossPrice: 10 to 12", "grossPrice: 50 to 60"]]`

**Comment by krzysztofwolski** [comment]
@JannikZed @tilman Latest version of the Search app has added a feature to apply facet configuration to the indices automatically (https://github.com/saleor/apps/pull/932). It should be a good starting point which can be later fine-tuned in the Algolia Dashboard, or on the frontend part (as Tilman mentioned, thanks for the examples!). If any of the facets should not be displayed, it can be modified in the index settings too (Facet display tab)

@tilman Thank you for reporting, indeed, the naming is confusing. Created a separate ticket fir this request #945

**Comment by lkostrowski** [comment]
@JannikZed please play with the latest app and feel free to open new issues if you have more ideas
